removed internal redis server

diff --git a/assets/init b/assets/init
--- a/assets/init
+++ b/assets/init
@@ -68,9 +68,16 @@ if [ -n "${REDISIO_PORT_6379_TCP_ADDR}" ]; then
   REDIS_PORT=${REDIS_PORT:-${REDISIO_PORT_6379_TCP_PORT}}
 fi
 
-# fallback to using internal redis server
-REDIS_HOST=${REDIS_HOST:-localhost}
+# fallback to default redis port
 REDIS_PORT=${REDIS_PORT:-6379}
+
+if [ -z "${REDIS_HOST}" ]; then
+  echo "ERROR: "
+  echo "  Please configure the redis connection."
+  echo "  Refer http://git.io/PMnRSw for more information."
+  echo "  Cannot continue without a redis connection. Aborting..."
+  exit 1
+fi
 
 # is a mysql or postgresql database linked?
 # requires that the mysql or postgresql containers have exposed
@@ -195,11 +202,6 @@ if [ "${DB_HOST}" == "localhost" ]; then
     echo "CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` DEFAULT CHARACTER SET \`utf8\` COLLATE \`utf8_unicode_ci\`;" | mysql -uroot ${DB_PASS:+-p$DB_PASS}
     echo "GRANT SELECT, LOCK TABLES, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER ON \`${DB_NAME}\`.* TO 'root'@'localhost';" | mysql -uroot ${DB_PASS:+-p$DB_PASS}
   fi
-fi
-
-if [ "${REDIS_HOST}" == "localhost" ]; then
-  echo "Starting redis server..."
-  supervisorctl start redis-server >/dev/null
 fi
 
 # configure nginx
@@ -335,8 +337,6 @@ appStop() {
   supervisorctl stop nginx >/dev/null
   echo "Stopping mysqld..."
   supervisorctl stop mysqld >/dev/null
-  echo "Stopping redis-server..."
-  supervisorctl stop redis-server >/dev/null
   echo "Stopping supervisord..."
   kill -15 $(cat /var/run/supervisord.pid)
   exit
