init: wait for database server to come online

diff --git a/assets/init b/assets/init
--- a/assets/init
+++ b/assets/init
@@ -349,6 +349,29 @@ fi
 chown gitlab_ci:gitlab_ci ${DATA_DIR}
 
 appStart () {
+  # due to the nature of docker and its use cases, we allow some time
+  # for the database server to come online.
+  case "${DB_TYPE}" in
+    mysql)
+      prog="mysqladmin -h ${DB_HOST} -u ${DB_USER} ${DB_PASS:+-p$DB_PASS} status"
+      ;;
+    postgres)
+      prog=$(find /usr/lib/postgresql/ -name pg_isready)
+      prog="${prog} -h ${DB_HOST} -U ${DB_USER} -d ${DB_NAME} -t 1"
+      ;;
+  esac
+  timeout=60
+  while ! ${prog} >/dev/null 2>&1
+  do
+    timeout=$(expr $timeout - 1)
+    if [ $timeout -eq 0 ]; then
+      echo "Could not connect to mysql server. Aborting..."
+      exit 1
+    fi
+    echo "Waiting for database server to accept connections..."
+    sleep 1
+  done
+
   if [ "$DB_INIT" == "yes" ]; then
     sudo -u gitlab_ci -H bundle exec rake db:setup RAILS_ENV=production
   fi
